// Code generated by "generate_embed"; DO NOT EDIT.
package main

var queries = map[string]string{
	"insert.sql": "insert into announces(\n    href,\n    title,\n    price,\n    published_at,\n    urgent,\n    department,\n    city,\n    district\n) values($1, $2, $3, $4, $5, $6, $7, $8)\non conflict do nothing;",
	"select.sql": "select\n    href,\n    title,\n    price,\n    published_at,\n    urgent,\n    department,\n    city,\n    district\nfrom announces;",
}
var templates = map[string]string{
	"index.html": "<table border=\"1\">\n    <tr>\n        <th align=\"center\">href</th>\n        <th align=\"center\">title</th>\n        <th align=\"center\">price</th>\n        <th align=\"center\">published_at</th>\n        <th align=\"center\">urgent</th>\n        <th align=\"center\">department</th>\n        <th align=\"center\">city</th>\n        <th align=\"center\">district</th>\n    </tr>\n    {{range .}}\n    <tr valign=\"top\">\n        <td align=\"left\"><a href=\"{{.Href}}\">{{.Href}}</a></td>\n        <td align=\"left\">{{.Title}}</td>\n        <td align=\"right\">{{if .Price}}{{.Price}}{{end}}</td>\n        <td align=\"left\">{{.PublishedAt}}</td>\n        <td align=\"left\">{{.Urgent}}</td>\n        <td align=\"left\">{{.Department}}</td>\n        <td align=\"left\">{{.City}}</td>\n        <td align=\"left\">{{.District}}</td>\n    </tr>\n    {{end}}\n</table>",
}
